Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end

  config.vm.define "bang-dev1" do |node|
    node.vm.box = "ubuntu/trusty64"
    node.vm.network :private_network, ip: "192.168.50.10"
    node.ssh.insert_key = false
  end
end
