Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end

  config.vm.define "avante-as1" do |node|
    node.vm.box = "ubuntu/trusty64"
    node.vm.network :private_network, ip: "192.168.50.10"
    node.ssh.insert_key = false

    node.vm.provision :shell, :path => "./as_setup.sh", :privileged => true
  end
end
